const thresholdMasses = [
  
    {
        "individualNamesOfDangerousSubstances": "Амонію нітрат (пункт 2 примітки)",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "2500",
            "secondClass": "5000",
            "firstClass": "10000",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Амонію нітрат (пункт 3 примітки)",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "312.5",
            "secondClass": "1250",
            "firstClass": "5000",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Амонію нітрат (пункт 4 примітки)",
        "CASnumber": "",
    "thresholdMassNorm": { "thirdClass": "49",
      "secondClass": "350",
      "firstClass": "2500",
  },
    },
    {
        "individualNamesOfDangerousSubstances": "Амонію нітрат (пункт 5 примітки)",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "2",
            "secondClass": "10",
            "firstClass": "50",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Калію нітрат (пункт 6 примітки)",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "2500",
            "secondClass": "5000",
            "firstClass": "10000",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Калію нітрат (пункту 7 примітки)",
        "CASnumber": "",
    "thresholdMassNorm": { "thirdClass": "312.5",
      "secondClass": "1250",
      "firstClass": "5000",
  },
    },
    {
        "individualNamesOfDangerousSubstances": "Миш’яку пентаоксид, миш’якова кислота (V) та/або солі миш’яку",
        "CASnumber": "1303-28-2",
        "thresholdMassNorm": { "thirdClass": "0.5",
            "secondClass": "1",
            "firstClass": "2",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Миш’яку триоксид, миш’яковиста (III) кислота та/або солі миш’яку",
        "CASnumber": "1327-53-3",
        "thresholdMassNorm": { "thirdClass": "",
            "secondClass": "",
            "firstClass": "0.1",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Бром",
        "CASnumber": "7726-95-6",
    "thresholdMassNorm": { "thirdClass": "4",
      "secondClass": "20",
      "firstClass": "100",
  },
    },
    {
        "individualNamesOfDangerousSubstances": "Хлор",
        "CASnumber": "7782-50-5",
        "thresholdMassNorm": { "thirdClass": "4",
            "secondClass": "10",
            "firstClass": "25",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Сполуки нікелю в інгальованій порошкоподібній формі:нікелю, монооксиднікелю, діоксиднікелю, сульфідтринікелю, дисульфіддинікелю, триоксид",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "",
            "secondClass": "",
            "firstClass": "1",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Етиленімін",
        "CASnumber": "151-56-4",
    "thresholdMassNorm": { "thirdClass": "5",
      "secondClass": "10",
      "firstClass": "20",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Фтор (флуор)",
        "CASnumber": "7782-41-4",
        "thresholdMassNorm": { "thirdClass": "5",
            "secondClass": "10",
            "firstClass": "20",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Формальдегід (концентрація ≥ 90 відсотків)",
        "CASnumber": "50-00-0",
        "thresholdMassNorm": { "thirdClass": "0.5",
            "secondClass": "5",
            "firstClass": "50",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Водень",
        "CASnumber": "1333-74-0",
    "thresholdMassNorm": { "thirdClass": "0.5",
            "secondClass": "5",
            "firstClass": "50",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Хлороводень (зріджений газ)",
        "CASnumber": "7647-01-0",
        "thresholdMassNorm": { "thirdClass": "2.5",
            "secondClass": "25",
            "firstClass": "250",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Алкіли свинцю",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "0.5",
            "secondClass": "5",
            "firstClass": "50",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Зріджені займисті гази, категорія 1 або 2 (зокрема, зріджений нафтовий газ) і природний газ (примітка 8)",
        "CASnumber": "",
    "thresholdMassNorm": { "thirdClass": "12.5",
      "secondClass": "50",
      "firstClass": "200",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Ацетилен",
        "CASnumber": "74-86-2",
        "thresholdMassNorm": { "thirdClass": "0.5",
            "secondClass": "5",
            "firstClass": "50",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Етилену оксид",
        "CASnumber": "75-21-8",
        "thresholdMassNorm": { "thirdClass": "0.5",
            "secondClass": "5",
            "firstClass": "50",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Пропілену оксид",
        "CASnumber": "75-56-9",
    "thresholdMassNorm": { "thirdClass": "0.5",
            "secondClass": "5",
            "firstClass": "50",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Метанол",
        "CASnumber": "67-56-1",
        "thresholdMassNorm": { "thirdClass": "50",
            "secondClass": "500",
            "firstClass": "5000",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "4,4′-метилен-біс (2-хлоранілін) та/або солі в порошкоподібній формі",
        "CASnumber": "101-14-4",
        "thresholdMassNorm": { "thirdClass": "",
            "secondClass": "",
            "firstClass": "0.01",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Метилізоціанат",
        "CASnumber": "624-83-9",
    "thresholdMassNorm": { "thirdClass": "",
      "secondClass": "",
      "firstClass": "0.15",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Кисень",
        "CASnumber": "7782-44-7",
        "thresholdMassNorm": { "thirdClass": "20",
            "secondClass": "200",
            "firstClass": "2000",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "2,4-толуол диізоціанат",
        "CASnumber": "584-84-9",
        "thresholdMassNorm": { "thirdClass": "1",
            "secondClass": "10",
            "firstClass": "100",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "2,6-толуол диізоціанат",
        "CASnumber": "91-08-7",
    "thresholdMassNorm": { "thirdClass": "1",
            "secondClass": "10",
            "firstClass": "100",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Карбоніл дихлорид (фосген)",
        "CASnumber": "75-44-5",
        "thresholdMassNorm": { "thirdClass": "0.12",
            "secondClass": "0.03",
            "firstClass": "0.75",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Арсин (тригідрид арсену)",
        "CASnumber": "7784-42-1",
        "thresholdMassNorm": { "thirdClass": "0.04",
            "secondClass": "0.2",
            "firstClass": "1",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Фосфін (тригідрид фосфору)",
        "CASnumber": "7803-51-2",
    "thresholdMassNorm": { "thirdClass": "0.04",
            "secondClass": "0.2",
            "firstClass": "1",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Дихлорид сірки",
        "CASnumber": "10545-99-0",
        "thresholdMassNorm": { "thirdClass": "",
            "secondClass": "",
            "firstClass": "1",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Триоксид сірки",
        "CASnumber": "7446-11-9",
        "thresholdMassNorm": { "thirdClass": "3",
            "secondClass": "15",
            "firstClass": "75",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Поліхлордибензофурани і поліхлордибензодіоксини (зокрема, ТХДД), обчислені в еквіваленті ТХДД (пункт 9 примітки)",
        "CASnumber": "",
    "thresholdMassNorm": { "thirdClass": "",
      "secondClass": "",
      "firstClass": "0.001",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: 4-амінобіфеніл та/або його солі",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: бензотрихлорид, бензидин та/або солі біс (хлорметиловий) ефір хлордиметиловий ефір",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: 1,2-дибромметан",
        "CASnumber": "",
    "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: диетилсульфат",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: диметилсульфат",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: диметилкарбамоілхлорид 1,2-дибром-3-хлор-пропан 1,2-диметилгідразін",
        "CASnumber": "",
    "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: диметилнітрозамін",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: гексаметилфосфотриамід",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: гідразин 2-нафтиламін та/або його солі 4-нітродифеніл" ,
        "CASnumber": "",
    "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Канцерогени або суміші, що містять такі канцерогени в концентраціях вище 5 відсотків за масою: 1,3-пропансультон",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "0.125",
            "secondClass": "0.5",
            "firstClass": "2",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Нафтопродукти та альтернативні види палива",
        "CASnumber": "",
        "thresholdMassNorm": { "thirdClass": "250",
            "secondClass": "2500",
            "firstClass": "25 000",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Безводний аміак",
        "CASnumber": "7664-41-7",
    "thresholdMassNorm": { "thirdClass": "12.5",
      "secondClass": "50",
      "firstClass": "200",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Трифтористий бор",
        "CASnumber": "7637-07-2",
        "thresholdMassNorm": { "thirdClass": "1.25",
            "secondClass": "5",
            "firstClass": "20",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Сірководень",
        "CASnumber": "7783-06-4",
        "thresholdMassNorm": { "thirdClass": "1.25",
            "secondClass": "5",
            "firstClass": "20",
        },
        },
    {
        "individualNamesOfDangerousSubstances": "Піперидин",
        "CASnumber": "110-89-4",
    "thresholdMassNorm": { "thirdClass": "12.5",
      "secondClass": "50",
      "firstClass": "200",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Біс(2-диметиламіноетил) (метил)амін",
        "CASnumber": "3030-47-5",
        "thresholdMassNorm": { "thirdClass": "12.5",
      "secondClass": "50",
      "firstClass": "200",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "3-(2-етилгексилокси) пропіламін",
        "CASnumber": "5397-31-9",
        "thresholdMassNorm": { "thirdClass": "12.5",
      "secondClass": "50",
      "firstClass": "200",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Cуміші (пункт 11 примітки) гіпохлориту натрію, які віднесено до гостро небезпечних для водного середовища категорії 1 з характеристикою небезпеки H400 (дуже токсично для водних) із вмістом активного хлору менш як 5 відсотків активного хлору і не віднесених до будь-яких інших категорій небезпеки",
        "CASnumber": "",
    "thresholdMassNorm": { "thirdClass": "80",
      "secondClass": "200",
      "firstClass": "500",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Пропіламін (пункт 10 примітки)",
        "CASnumber": "107-10-8",
        "thresholdMassNorm": { "thirdClass": "125",
            "secondClass": "500",
            "firstClass": "2000",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Трет-бутилакрилат (пункт 10 примітки)",
        "CASnumber": "1663-39-4",
        "thresholdMassNorm": { "thirdClass": "80",
            "secondClass": "200",
            "firstClass": "500",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "2-метил-3-бутен-нітрил (пункт 10 примітки)",
        "CASnumber": "16529-56-9",
    "thresholdMassNorm": { "thirdClass": "125",
      "secondClass": "500",
      "firstClass": "200",
  },
  
    },
    {
        "individualNamesOfDangerousSubstances": "Тетрагідро-3,5-диметил-1,3,5,-тіадіазин-2-тіон (Дазомет) (пункт 10 примітки)",
        "CASnumber": "533-74-4",
        "thresholdMassNorm": { "thirdClass": "50",
            "secondClass": "100",
            "firstClass": "200",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "Метилакрилат (пункт 10 примітки)",
        "CASnumber": "96-33-3",
        "thresholdMassNorm": { "thirdClass": "125",
            "secondClass": "500",
            "firstClass": "2000",
        },
    },
    {
        "individualNamesOfDangerousSubstances": "3-метилпіридин (пункт 10 примітки)",
        "CASnumber": "108-99-6",
    "thresholdMassNorm": { "thirdClass": "125",
            "secondClass": "500",
            "firstClass": "2000",
  },
    },
    {
        "individualNamesOfDangerousSubstances": "1-бром-3-хлорпропан (пункт 10 примітки)",
        "CASnumber": "109-70-6",
    "thresholdMassNorm": { "thirdClass": "125",
            "secondClass": "500",
            "firstClass": "2000",
  },
    },
  ]

export { thresholdMasses };